spring:
  datasource:
#    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
#    username: postgres.jfwbldocxafjzxhufaqm
#    password: postgres5784
    url: jdbc:postgresql://localhost:5432/cardtopia_db
    username: postgres
    password: 5784
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  secret: afafa876saf876saf876as8sf6s87as6f7fas6fas78f6
  access-ms: 1200000 #20 min
  refresh-ms: 6000000 #100 min
server:
  port: 8080
